import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Header/Header";
import { Footer } from "@/Footer/Footer";
import { Menu } from "@/Menu/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IPL Clone App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Menu/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
